---
title: "Quiz 1 - Week 1 - R Programming Coursera"
output: rmarkdown::github_document
---
1. The R language is a dialect of which of the following programming languages?
-> S

2. The definition of free software consists of four freedoms (freedoms 0 through 3). Which of the following is NOT one of the freedoms that are part of the definition?  Select all that apply.
- Definition: “Free software” means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software.

Pick:
- The freedom to prevent users from using the software for undesirable purposes.
- The freedom to sell the software for any price.
- The freedom to restrict access to the source code for the software.

3. Question 3

In R the following are all atomic data types EXCEPT: (Select all that apply)
Pick: 
- data frame
- list

4. If I execute the expression x <- 4 in R, what is the class of the object `x' as determined by the `class()' function?
- numeric

5. What is the class of the object defined by x <- c(4, TRUE)?
- numeric

6. If I have two vectors x <- c(1,3, 5) and y <- c(3, 2, 10), what is produced by the expression cbind(x, y)?
- a matrix with 2 columns and 3 rows

7. A key property of vectors in R is that
- elements of a vector all must be of the same class

8. I have a list defined as x <- list(2, "a", "b", TRUE). What does x[[2]] give me? Select all that apply.
Pick:
    - a character vector containing the letter "a".
    - a character vector of length 1.

9. Suppose I have a vector x <- 1:4 and y <- 2:3. What is produced by the expression x + y?
- an integer vector with the values 3, 5, 5, 7.

10. Suppose I have a vector x <- c(17, 14, 4, 5, 13, 12, 10) and I want to set all elements of this vector that are greater than 10 to be equal to 4. What R code achieves this? Select all that apply.
- x[x > 10] <- 4
- x[x >= 11] <- 4

11-20.

```{r}
csv <- read.csv("hw1_data.csv")
csv

names(csv)
#[Question 11] "Ozone"   "Solar.R" "Wind"    "Temp"    "Month"   "Day" 

csv[1:2, ] #Question 12
#   Ozone Solar.R Wind Temp Month Day
# 1    41     190  7.4   67     5   1
# 2    36     118  8.0   72     5   2

length(csv[,1])
#[Question 13] 153

csv[(length(csv[,1])-1) : (length(csv[,1])),]
#     Ozone Solar.R Wind Temp Month Day
# 152    18     131  8.0   76     9  29
# 153    20     223 11.5   68     9  30
#Question 14

csv[47,]
#   Ozone Solar.R Wind Temp Month Day
#47    21     191 14.9   77     6  16
# Question 15

sum(is.na(csv[,1]))
#[Question 16] 37

use <- !is.na(csv[,1])
mean(csv[use, 1])
#[Question 17] 42.12931

subSet <- subset(csv, Ozone > 31 & Temp > 90)
mean(subSet[, "Solar.R"])
# [Question 18] 212.8

subSet <- subset(csv, Month == 6)
mean(subSet[, "Temp"])
#[Question 19] 79.1

subSet <- subset(csv, Month == 5)
subSet
max(subSet[, "Ozone"], na.rm = TRUE)
#[Question 20] 115
```